name: Release npm package
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        description: 'Release type:'
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Configure Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.6.0'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub-Actions"

      - name: Install dependencies
        run: npm install

      - name: Bump version and generate changelog using standard-version
        id: version_bump
        run: |
          npm run release -- --release-as $RELEASE_TYPE
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release-type }}

      - name: Commit and tag the release
        run: |
          git push origin
          git push origin --tags

      - name: Publish to npm
        run: |
          npm install
          npm run build:lib
          cd dist/drag-drop-layout
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
          name: Release ${{ env.NEW_VERSION }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
